name: Test running

on:
  push:
  pull_request:
    paths:
        - src/**
        - tests/**
    branches:
      - main
  merge_group:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build the package
        run: bun run build

      - name: Test
        run: bun test